// wordlist.h -- the BIP-39 word list and small string helpers. Adapted from
// znn-bruteforce-cuda, minus the search-template machinery this tool has no
// use for. Seed derivation is only defined for the built-in English list; a
// custom list must still be 2048 ASCII words of at most 8 characters (the
// width the GPU word table is sized for).
#ifndef WORDLIST_H
#define WORDLIST_H

#include <cctype>
#include <fstream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "bip39_words.h"

const int MAX_WORD_LEN = 8;

// A 256-bit entropy mnemonic, as generated by newRandomKeyStore in
// znn-address-generator-go: 32 entropy bytes plus an 8-bit checksum, split
// into 24 eleven-bit word indices.
const int ENTROPY_BYTES = 32;
const int MNEMONIC_WORDS = 24;

inline std::string to_lower(std::string s) {
    for (char& c : s) c = (char)tolower((unsigned char)c);
    return s;
}

inline std::string trim(const std::string& s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    if (a == std::string::npos) return "";
    size_t b = s.find_last_not_of(" \t\r\n");
    return s.substr(a, b - a + 1);
}

inline std::vector<std::string> split_fields(const std::string& s) {
    std::vector<std::string> out;
    std::istringstream is(s);
    std::string w;
    while (is >> w) out.push_back(w);
    return out;
}

// load_wordlist returns the built-in English list, or a custom 2048-word list
// read from `path`.
inline std::vector<std::string> load_wordlist(const std::string& path) {
    std::vector<std::string> words;
    if (path.empty()) {
        words.reserve(2048);
        for (int i = 0; i < 2048; i++) words.emplace_back(BIP39_WORDS[i]);
        return words;
    }

    std::ifstream f(path);
    if (!f) throw std::runtime_error("could not open " + path);
    std::string line;
    while (std::getline(f, line)) {
        std::string w = trim(line);
        if (!w.empty()) words.push_back(w);
    }
    if (words.size() != 2048)
        throw std::runtime_error(path + " holds " + std::to_string(words.size()) +
                                 " words, a BIP-39 list must hold 2048");
    for (const auto& w : words)
        if (w.size() > (size_t)MAX_WORD_LEN)
            throw std::runtime_error("word \"" + w + "\" is longer than " +
                                     std::to_string(MAX_WORD_LEN) + " characters (unsupported)");
    return words;
}

inline std::map<std::string, int> word_index(const std::vector<std::string>& words) {
    std::map<std::string, int> m;
    for (int i = 0; i < (int)words.size(); i++) m[words[i]] = i;
    return m;
}

#endif  // WORDLIST_H
